#!/bin/bash

if [ ! -f composer.phar ]; then
    curl -sS https://getcomposer.org/installer | php
fi

if [ ! -d vendor ]; then
    php composer.phar install --dev
fi

phpunit --bootstrap=vendor/autoload.php tests
